### ISSUE TITLE
Add Google Analytics tracking for metrics

### ISSUE THREAD

**Issue by adamjcook** [smevirtual/website#3]
- [ ] Add "Cookie Notice" banner to bottom of page (GDPR requirement).
- [x] Add Google Analytics tracking code.
- [x] Add required legal notices on user privacy/data collection.

**Comment by adamjcook** [comment]
Closed in favor of #23
